on: push
name: Main Workflow
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: |
              mvn -B package --file Projeto1/backend/pom.xml
      - uses: actions/upload-artifact@v1
        with:
          name: target
          path: Projeto1/backend/target
  sonarcloud:
    name: SonarQube Trigger
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@v1
      with:
        name: target
        path: Projeto1/backend/target
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: Projeto1/backend
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
